version: '3.8'
services:
  app:
    build: .
    ports:
      - "3453:3453"
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo:27017/testdatabase
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
